### ISSUE TITLE
loop() is not working with stereo files

### ISSUE THREAD

**Issue by SoerenNorge** [processing/processing-sound-archive#101]
Hi

I'm having a issue with the loop() and stereofiles. It plays the soundfile once, and stops throwing the error: ERROR: /node/set: Synth 1 not found

I've tried using wav, aif, and mp3. But none of them works in stereo, only in mono.

Hope there's a fix for it

`import processing.sound.*;
SoundFile soundscape;

void setup() {
  size(640, 360);
  background(255);

  // Load a soundfile from the /data folder of the sketch and play it back
  soundscape = new SoundFile(this, "soundscape.wav");
  soundscape.loop();

}      
void draw() {
}`

**Comment by slambert** [comment]
Duplicate? https://github.com/processing/processing-sound/issues/55
