### ISSUE TITLE
Audio Output Channel 

### ISSUE THREAD

**Issue by ThomasLengeling** [processing/processing-sound-archive#105]
Hello,
I have questions, would it be possible to send audio to a specific audio output channel with the library. I know that I can read different Input channels but would be it possible to send from one input channel to a specific output channel. Thank you!

**Comment by wirsing** [comment]
@ThomasLengeling this is not possible at the moment, you would have to route the channels in your soundcard mixer or with a seperate software router. It's noted as a feature for the future.
