### ISSUE TITLE
[SOLVED] Issues compiling in Ubuntu 14

### ISSUE THREAD

**Issue by PauloBarbeiro** [processing/processing-sound-archive#26]
Hi all!
I am trying to test processing-sound in ubuntu, but no success in using, nor compliling.
Let me share some stuff.

The first attempt were simple but in the libraries folder, and see the magic. Unfortunately, it didn't work. ;)

Then I ran the 'make install'. As advised in the project description. But it failed with this message:
cp libMethClaInterface.so ../../library/linux64
cp: cannot stat ‘libMethClaInterface.so’: No such file or directory
make: **\* [install] Error 1

At that moment, I checked the folder, and the file libMethClaInterface.so was already in there. 
So I, thought I could try to run the ant command in the root folder, but: 

Buildfile: /home/paulo/sketchbook/libraries/processing-sound-master/build.xml
compile:
BUILD FAILED
/home/paulo/sketchbook/libraries/processing-sound-master/build.xml:13: Please build the core library first and make sure it sits in ../processing/core/library/core.jar
Total time: 0 seconds

OK! Then, I went try to compile, using 'make all'. BTW, using Ubuntu 14.04 64bits, Java Oracle 7. The first return message was, that it could not find the jni.h... I took a look at the MakeFile_Linux_64. It wasn't fine for my system, I've changed the compiler flags to address the proper locations: 
gcc -fPIC -I/usr/lib/jvm/java-7-oracle/include/linux -I./include -I/lib/jvm/java-7-oracle/include

Even this way the compiler couldn't find the jni.h... =P I did a stupid move: I made a copy of jni.h, in the cpp/include folder. And it passed that error, but then, it is complaining that can not find the -lmethcla tag in the second line: 
gcc -shared -o libMethClaInterface.so *.o -lmethcla;

So... I am stuck now. If someone could point me to a solution. I would love!
Thank you! :)

**Comment by wirsing** [comment]
Hi Paolo! You don't need to compile the libraries yourself, if you want to you just need to use the -L flag and provide the path to the library. I just released an updated version of the library, there might be a problem with the availability through the library installer. try to install this one manually and please let me know if it worked: https://github.com/processing/processing-sound/releases/tag/v1.1

**Comment by PauloBarbeiro** [comment]
Oh Yeah! It's working!! No bugs thus far. 
If I found some bug, I will report you.
Thank you!
