### ISSUE TITLE
Not working on 64 bit linux (Archlinux / Mint) processing-3.0a5

### ISSUE THREAD

**Issue by monkstone** [processing/processing-sound-archive#27]
Whether true or not the console message I get is:-
`A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit  application.`

But when I look at library folder the 64 bit libraries seem to be included?

**Comment by wirsing** [comment]
did you checkout the latest version? should work since v1.1. Please let me know if it doesn't.

https://github.com/processing/processing-sound/releases/tag/v1.2

**Comment by monkstone** [comment]
Version 1.1 was what I tested above. I tried but failed to compile version 1.2 missing -lmethcla on archlinux for cpp compile (using netbeans to compile java side me eclipse and I never get on)

**Comment by wirsing** [comment]
you don't need to compile anything, can you try to install through the library manager?

**Comment by monkstone** [comment]
That is how installed it originally, to try to be helpful I tried to compile it 1.2 installed through library manager also failing ...................

**Comment by wirsing** [comment]
i just uploaded a new release, seems there was a problem with the symlinks in the folder. it should be showing up on the library manager as update soon, you can also download it here: 

https://github.com/processing/processing-sound/releases/download/v1.2.1/sound.zip

**Comment by monkstone** [comment]
@wirsing
Confirmed as fixed with this version. You may be marginally interested that I get unusual set of error messages if I close sketch at window instead of from ide.
PS see example translated to ruby-processing:-
http://learning-ruby-processing.blogspot.co.uk/2015/01/testing-new-processing-sound-library-in.html

**Comment by REAS** [comment]
@monkstone That is also processing/processing-sound#9
