### ISSUE TITLE
mp3 playback error OSX 10.9.5 Processing 3.0a4

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing-sound-archive#28]
I get an error when I wanted to play an mp3 file. I've converted the vibraphon.aiff to an mp3 (and shortened the length a bit). I've also played with different frequencies (44100, 48000) and mono and stereo. A different mp3 gave errors as well, so I think it's related to mp3?

The error message:

```
Could not run the sketch: 

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: File contains data in an unknown format.
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.
```

The audiofile: https://dl.dropboxusercontent.com/u/1147392/vibraphon.mp3

**Comment by wirsing** [comment]
Did you check out the latest release? This is fixed, please let me know if it works for you.

https://github.com/processing/processing-sound/releases/tag/v1.2

**Comment by kasperkamperman** [comment]
How do I remove the installed Sound library from the Processing application 3.0a4? Or should I use 3.0a5 where the library isn't included anymore?

**Comment by wirsing** [comment]
If you want to use 3.0a4 you need to delete from inside the Application Bundle. You can either open the Application Bundle in the finder or cd into it from the Terminal. The library should be in /Contents/Java/modes/java/libraries. You should use the newest Processing Version anyway though.

**Comment by REAS** [comment]
Yes, it's best to use 3a5 and to get the Library through Add Library... in the Sketch menu.

**Comment by wjsandbe** [comment]
@wirsing sorry I'm newb, what do I do with these files once I download em?
https://github.com/processing/processing-sound/releases/tag/v1.2
