### ISSUE TITLE
FFT API

### ISSUE THREAD

**Issue by shiffman** [processing/processing-sound-archive#32]
At one time we had discussed making a revision to FFT to embed the spectrum array and the # of bands inside the FFT object.  I am finalizing the following example for Learning Processing 2nd edition.

Current working code:

```
SoundFile sample;
FFT fft;
int bands = 128;
float[] spectrum = new float[bands];

void setup() {
  sample = new SoundFile(this, "beat.aiff");
  sample.loop();
  fft = new FFT(this);
  fft.input(sample, bands);
}

void draw() {
  fft.analyze(spectrum);
  for (int i = 0; i < bands; i++) {
    stroke(50);
    float y = map(spectrum[i], 0, 1, height * 0.75, 0);
    line(i, height * 0.75, i, y);
  }
}
```

Proposed changed code:

```
SoundFile sample;
FFT fft;
int bands = 128;

void setup() {
  sample = new SoundFile(this, "beat.aiff");
  sample.loop();
  fft = new FFT(this, bands);   
  fft.input(sample);
}

void draw() {
  fft.analyze();
  for (int i = 0; i < fft.size(); i++) {
    stroke(50);
    float y = map(fft.spectrum[i], 0, 1, height * 0.75, 0);
    line(i, height * 0.75, i, y);
  }
}
```

This more closely mirrors how the Amplitude object works (though admittedly it's a great deal simpler with only one number to return).  I also find that students are often confused by code where they have to make/maintain their own array which is then filled by passing it as an argument to a function.

I just checked and [p5.js does it a slightly different way](http://p5js.org/reference/#/p5.FFT) but a bit closer to the above.  The thing to avoid  as I understand it performance-wise is making an entirely new array each time in `draw()`.

Thoughts?

**Comment by wirsing** [comment]
It would definitely be easier to handle this way for beginners, I suggested it like this in the very beginning stages of the lib, too. After initial discussions it was suggested to pass an array to not allocate a new array full of floats for every frame.  For performance the passing of the array into the object makes much more sense.

**Comment by shiffman** [comment]
Couldn't the FFT object internally store a single array which is updated whenever `analyze()` is called and thus not allocate a new array for each frame?  (We could also overload `analyze()` so that for more advanced scenarios one can pass a different array to be filled.)

**Comment by wirsing** [comment]
As far as I understand, the array return is the problem. Instead of returning an array every draw loop it will be written directly into the one which is passed. So storing it in the object wouldn't help. Ben commented in the very beginning of the development process.

**Comment by REAS** [comment]
Let's bring @benfry in to this to clarify. Ben?

**Comment by shiffman** [comment]
Just to be clear this is the change I'm proposing: https://github.com/shiffman/processing-sound/commit/5a33034c54886182d3cc85e6e96ea8e0dde80ca5 (apologies for the indentation inconsistencies).

It does not return an array but rather stores it internally in the `FFT` object so the performance should be identical.  The `analyze()` function is overloaded so that Processing user can use his/her own array instead if preferable.  

Here is a portion of the FFT class with the new relevant sections:

```
public class FFT {

  private int fftSize;
  public float[] spectrum;

  public FFT(PApplet theParent, int fftSize_) {
    fftSize = fftSize_;
    spectrum = new float[fftSize];
  }

  public void analyze(){
    float[] m_value = m_engine.poll_fft(ptr);
    int num_samples = Math.min(spectrum.length, m_value.length);
    for(int i=0; i<num_samples; i++){
      spectrum[i] = m_value[i];
    }
  }

  public void analyze(float[] value){
    float[] m_value = m_engine.poll_fft(ptr);
    int num_samples = Math.min(value.length, m_value.length);
    for(int i=0; i<num_samples; i++){
      value[i] = m_value[i];
    }
  }
}
```

I can clean this up and submit a pull request depending on what @benfry and @wirsing think, thanks!

**Comment by wirsing** [comment]
@shiffman maybe i'm missing something but how do you get the fft values out of the object then? The .spectrum getter would still have to return the array somehow? 

So I'm always confused with Java pass-by-reference vs pass-by-value. As far as I understand Java is always pass-by-value but instead of a copy of the value the ID/reference of an object is passed as a value. As soon as we have to make a copy of the fft array to return it we have a problem and it would be a bad idea to do it. When I return an array from a function it supposedly should return just a value/reference so we should be fine but apparently in this case it makes a copy. @benfry can you help us clarify?

**Comment by shiffman** [comment]
@wirsing you are correct Java is alway pass by value, however, when passing an object (or array) the copy is made of the reference not of the actual full thing itself.  So it's not that much of a performance hit as long as you do not allocate memory for a new array each cycle.  In any case, I'm not proposing we return the array, rather we make the spectrum array inside the `FFT` object public so that if can be accessed directly with dot syntax.  This is just like how we say `img.pixels` for a `PImage`.  You can see my example here:

https://gist.github.com/shiffman/01c393439ee95dae2f5c

**Comment by wirsing** [comment]
@shiffman exactly, that's how i also understand it. Ben still made a comment about it in the beginning so I was confused if there are special cases when copies are made.

Ah ok, i missed the part where you wanted to make the array public. I thought you wanted to introduce a getter method which returns the array. 

Alright, let's do it like this then?

**Comment by REAS** [comment]
Sounds like a good plan to me.

**Comment by wirsing** [comment]
merged and adjusted. will be in next release which is coming up soon. thx!

**Comment by shiffman** [comment]
Great, let me know how else I can help!
