### ISSUE TITLE
Can't find Sound library in the Library Manager

### ISSUE THREAD

**Issue by RitheshKumar** [processing/processing-sound-archive#35]
Not able to install/find sound library using Library Manager

**Comment by preziotte** [comment]
Came here to mention this as well, it's not showing up.

**Comment by REAS** [comment]
Where is it not showing up? The Sound library is only for Processing 3.0+. Are you using the latest alpha release or a 2.0 version?

**Comment by RitheshKumar** [comment]
Okay, did not know that for a fact! I use 2.2.1, the stable release that shows up on the download page. I believe that you must mention in your sound library page, that it is only available for 3.0 and above. Thanks!

**Comment by REAS** [comment]
Yes, I'm sorry that it wasn't mentioned there. I'll leave this open until that is fixed.

**Comment by preziotte** [comment]
Yep, had the same confusion.  Thanks a lot for the clarification!

**Comment by CyberianWolf** [comment]
Is it possible to record the sound or audio input from a microphone or a line-in and save it to a file using the processing-sound library? Not the minim library.  If yes, can I see an example?

**Comment by wirsing** [comment]
Hi,

no, not at this moment. It may be planned for the future.

all the best,
Wilm

**Comment by ForrestErickson** [comment]
I am not able to find any download for  Proccessing 3.0.
The Processing down load page goes to version 2.2.1 (19 May 2014). See; https://processing.org/download/?processing

This really situation could use a through how to document for someone to migrate from 2.2.1 to what ever works.

**Comment by REAS** [comment]
Please open a separate issue for each unique issue. This issue has moved off track. I re-named it to better reflect the initial question.

**Comment by ForrestErickson** [comment]
Thanks for renaming.
I will be happy to open a new issue and think it might be "Downloaded Windows 32 bit but Sound Library Error References 64 Bit".
Would that work?  

Do I copy notes from above or some how reference this issue?
Also see below for my reassessment of my problem with further insights as of today.

---

Trying to get Sound library on my Windows XP.  
I am trying to reconstruct what happened.
I have down loaded 32 bit 2.2.1 and 3.0a5 and 3.0a10.
Example folder name: processing-2.2.1-windows32

Today when I loaded and tried to run 2.2.1 Today I found it in the Sketch> Import Library>Sound I do not think it was there before.
I think it got there when I loaded it from either 3.0a5 or 3.0a10.
I had to navigate to the Sketch> Import Library > Add Library dialog and then set the filter Category filter to Sound.  I found it and added it.

Regardless now when I try to run it I get the error:
"A library used by this sketch is not installed properly."
"A library relies on native code that's not available.
Or only works properly when the sketch is run as a 64-bit  application."

The sketch I am trying to runs is from the on line examples: https://processing.org/reference/libraries/sound/SinOsc.html

import processing.sound.*;
SinOsc sine;

void setup() {
  size(640, 360);
  background(255);

  // Create the sine oscillator.
  sine = new SinOsc(this);
  sine.play();
}

void draw() {
}

**Comment by REAS** [comment]
Yes, please make a new Issue and we'll take it from there.

**Comment by ForrestErickson** [comment]
Done I think.
Hope I am not making a false alarm.
Love processing.

**Comment by REAS** [comment]
This was fixed. Will be online with the next update.
