### ISSUE TITLE
Building core.jar

### ISSUE THREAD

**Issue by tmwangi** [processing/processing-sound-archive#36]
I am trying to run the ant command but whenever i try to run it gives out an an error:

BUILD FAILED
libraries/processing-sound-master/build.xml:13: Please build the core library first and make sure it sits in ../processing/core/library/core.jar

I already ran make and make install. I am using a Mac OS by the way. Just wondering if I am missing something.

Thanks.

**Comment by joshuajnoble** [comment]
You should just be able to install the sound library from the Import Library Tool, like "Import Library" -> Add Library, then do Sound.

**Comment by wirsing** [comment]
to build the library you need to check out the processing source and have it ready in ../processing

there is no need to build the library though, the binaries are up and current.

cheers,
Wilm
