### ISSUE TITLE
error: unrecognized command line option ‘-std=c++11’

### ISSUE THREAD

**Issue by ewelinka** [processing/processing-sound-archive#37]
I try to compile and get this error

g++ -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers -I./include -std=c++11 -g -c processing_sound_MethClaInterface.cpp;  
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: **\* [all] Error 1

my gcc version is 4.6.3-1ubuntu5, does it have to do with the gcc version??

**Comment by wirsing** [comment]
why are you trying to build that library?

**Comment by ewelinka** [comment]
I think I had some problems with the installation and that's why I was trying to build the library. 
Now I was able to install it without problems, so I don't have this problem any more.
