### ISSUE TITLE
Downloaded Windows 32 bit but Sound Library Error References 64 Bit"

### ISSUE THREAD

**Issue by ForrestErickson** [processing/processing-sound-archive#41]
## These notes come from my original request for help on the Sound Library at https://github.com/processing/processing-sound/issues/35#issuecomment-118634836

Trying to get Sound library on my Windows XP.

I am trying to reconstruct what happened.
I have down loaded 32 bit 2.2.1 and 3.0a5 and 3.0a10.
Example folder name: processing-2.2.1-windows32

Today when I loaded and tried to run 2.2.1 Today I found it in the Sketch> Import Library>Sound I do not think it was there before.
I think it got there when I loaded it from either 3.0a5 or 3.0a10.
I had to navigate to the Sketch> Import Library > Add Library dialog and then set the filter Category filter to Sound. I found it and added it.

Regardless now when I try to run it I get the error:
"A library used by this sketch is not installed properly."
"A library relies on native code that's not available.
Or only works properly when the sketch is run as a 64-bit application."

The sketch I am trying to runs is from the on line examples: https://processing.org/reference/libraries/sound/SinOsc.html

import processing.sound.*;
SinOsc sine;

void setup() {
size(640, 360);
background(255);

// Create the sine oscillator.
sine = new SinOsc(this);
sine.play();
}

void draw() {
}

**Comment by wirsing** [comment]
Hi! Sorry for the late reply, for the moment Windows 32bit is not supported. I'm working on a fix for the future.

**Comment by wirsing** [comment]
Hi Eric,

we still have problems with Win32, any chance you can get hold of a 64bit Windows? v1.2.1. should work there.

thanks!
Wilm

**Comment by ForrestErickson** [comment]
Thanks for getting back to me. 
I can understand you not wanting to support the older platforms. I suggest that the non support for 32 bit versions be stated more clearly at the down load site.

**Comment by wirsing** [comment]
yes, sorry about that. I'll put that up! thanks!!

**Comment by nikAleksandr** [comment]
Another problem to bring up is this limits processing's use with the Raspberry Pi, for which there is only a 32-bit Processing.
