### ISSUE TITLE
cue() supposedly takes decimals (float), but it seems to treat them as integers

### ISSUE THREAD

**Issue by cplay** [processing/processing-sound-archive#43]
It'd be great if decimals worked for cueing songs to precise beats and such, but there's no difference in say cue(15.3), as in the example, and cue(15).

You can tell if you try going through the decimals with 15.1, 15.2, 15.3, etc. without hearing any change, and then suddenly a big change that's equivalent to substituting 16.

It'd be great if it took milliseconds instead, or even better would be samples. Otherwise, this library is really ready to make some great sample-based electronic music tools.

**Comment by wirsing** [comment]
this was a casting error. should be fixed now. I'm working on a seperate Audio Loop right now so we can do precise and faster scheduling for things like this. thanks for reporting!
