### ISSUE TITLE
sound.jar missing in deployment

### ISSUE THREAD

**Issue by jensstockhausen** [processing/processing-sound-archive#48]
Since version 1.3.1 the sound.jar is not included in the zip files provided. Version 1.3 is the last one containing the file. Thus the library can be installed but i not available in the Processing IDE.

Workaround: download the 1.3 from https://github.com/processing/processing-sound/releases/tag/v1.3 and unzip into you libraries folder of your sketchbook. 

Noticed on mac osx / Processing version 3.0 alpha (3.0b7)

**Comment by wirsing** [comment]
fixed

**Comment by jensstockhausen** [comment]
That was fast! 
Thanks ;-)
