### ISSUE TITLE
1.3.1 on Windows 10 crashes

### ISSUE THREAD

**Issue by ynaoto** [processing/processing-sound-archive#52]
I am using Processing 3 for Windows 64 bits on Win10 with Sound Lib 1.3.1, but most of samples crash. Here is a dump from AmplitudeRMS (stopped at line 25):
A library used by this sketch is not installed properly.
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.

Tried to use Processing 3 for Win 32, but got similar messages.

**Comment by shlomihod** [comment]
I do get the same Problem with Windows 7 with Processing 3 for 32 bit. I tried older version for the library, until 1.2 and it's not working.

I could make it works only with Processing 3 for 64 bit, with Sound Library v1.2.1.

**Comment by Rolembeek** [comment]
Where can I download v1.2.1 of sound library  ?
(running Processing 3   Win10     64bit)

**Comment by kaoskorobase** [comment]
Closing as duplicate of #3
