### ISSUE TITLE
UnsatisfiedLinkError: processing.sound.MethClaInterface.busConstructMono()I A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit application.

### ISSUE THREAD

**Issue by ryanpg** [processing/processing-sound-archive#66]
Ubuntu 16.04

Sound 1.3.1 The Processing Foundation  Sound library based on MethCla for Processing

uname -a
Linux ryanpg-Lenovo-Z70-80 4.2.0-27-lowlatency #32-Ubuntu SMP PREEMPT Fri Jan 22 05:55:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

UnsatisfiedLinkError: processing.sound.MethClaInterface.busConstructMono()I
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.

**Comment by StickyMickey** [comment]
Do you actually use linux? I was doing some digging, and I think that linux is the only os supported. I get the last 2 lines of your error when I try to use this library, and I run 64-bit windows.

**Comment by kaoskorobase** [comment]
@ryanpg This problem on Linux x86_64 is being tracked in issue #54, closing here.
