### ISSUE TITLE
Quality parameter on lowpass- and highness filter

### ISSUE THREAD

**Issue by wwagner4** [processing/processing-sound-archive#95]
I would need a quality parameter for the lowpass and highness filters in order to control the slope steepness.

**Comment by wirsing** [comment]
hi @wwagner4 you can change the bandwidth for the bandpass filter but HP and LP are all fixed orders for now.

**Comment by wwagner4** [comment]
:(

2017-08-09 17:56 GMT+02:00 Wilm Thoben <notifications@github.com>:
